apiVersion: v1
kind: Template
metadata:
  name: spring-pet-clinic
  annotations:
    openshift.io/display-name: Spring Boot Pet Clinic sample
    description: Spring Boot Pet Clinic sample using postgresql
    tags: spring,postgresql
    openshift.io/provider-display-name: IBM Client Dev Advocacy.
    openshift.io/documentation-url: https://github.com/ibmappmodernization/app-modernization-plants-by-websphere-jee6.git
    openshift.io/support-url: https://access.redhat.com
labels:
  app: petclinic-postgresql
parameters:
- name: APPLICATION_NAME
  displayName: Application name
  description: The name for the application.
  value: petclinic-postgresql
  required: true
- name: APPLICATION_PROFILE
  displayName: Application profile
  description: The Spring profile for the application.
  value: postgresql
  required: false
- name: APPLICATION_HOSTNAME
  displayName: Application hostname
  description: 'Custom hostname for service routes.  Leave blank for default hostname, e.g.: <application-name>.<project>.<default-domain-suffix>'
  value: ''
  required: false
- name: REPLICAS
  description: Number of replicas to spin up
  displayName: Number of replicas to spin up
  value: '1'
  required: true
- name: GIT_URI
  description: Git source URI for application
  displayName: Git source URI for application
  required: true
- name: GIT_BRANCH
  description: Git source branch for application
  displayName: Git source branch for application
  value: 'master'
  required: true
- name: PETCLINIC_DB_SERVICE
  displayName: Name of database service
  description: Name of database service
  value: postgresql
  required: true
- name: GENERIC_TRIGGER_SECRET
  displayName: Generic build trigger secret
  description: Generic build trigger secret
  from: "[a-zA-Z0-9]{8}"
  generate: expression
objects:
- apiVersion: v1
  kind: BuildConfig
  metadata:
    name: "${APPLICATION_NAME}"
    annotations:
      template.alpha.openshift.io/wait-for-ready: 'true'
  spec:
    triggers:
    - type: Generic
      generic:
        secret: "${GENERIC_TRIGGER_SECRET}"
    - type: ImageChange
      imageChange: {}
    source:
      type: Git
      git:
        uri: "${GIT_URI}"
        ref: "${GIT_BRANCH}"
    strategy:
      type: Docker
      dockerStrategy:
        from:
          kind: ImageStreamTag
          name: fabric8/java-centos-openjdk8-jre:latest
    output:
      to:
        kind: ImageStreamTag
        name: "${APPLICATION_NAME}:latest"
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    name: "${APPLICATION_NAME}"
  spec:
    lookupPolicy:
      local: false
  status:
    dockerImageRepository: ''
    tags:
    - tag: latest

- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    name: "${APPLICATION_NAME}"
    annotations:
      template.alpha.openshift.io/wait-for-ready: 'true'
    labels:
      deploymentConfig: "${APPLICATION_NAME}"
  spec:
    strategy:
      type: Recreate
    triggers:
    triggers:
     - type: ImageChange
       imageChangeParams:
         automatic: true
         containerNames:
         - "${APPLICATION_NAME}"
         from:
           kind: ImageStreamTag
           name: "${APPLICATION_NAME}:latest"
     - type: ConfigChange
    replicas: ${REPLICAS}
    selector:
      deploymentConfig: "${APPLICATION_NAME}"
    template:
      metadata:
        labels:
          deploymentConfig: "${APPLICATION_NAME}"
      spec:
        containers:
        - name: "${APPLICATION_NAME}"
          image: "${APPLICATION_NAME}"
          ports:
          - name: http
            containerPort: 8080
            protocol: TCP
          - name: hazelcast
            containerPort: 5701
            protocol: TCP
          env:
          - name: SPRING_PROFILES_ACTIVE
            value: "${APPLICATION_PROFILE}"
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                key: database-user
                name: "${PETCLINIC_DB_SERVICE}"
          - name: DB_PORT
            value: '5432'
          - name: DB_HOST
            value: "${PETCLINIC_DB_SERVICE}"
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                key: database-password
                name: "${PETCLINIC_DB_SERVICE}"
          resources:
            limits:
              cpu: 300m
              memory: 300Mi
            requests:
              cpu: 5m
              memory: 250Mi
          imagePullPolicy: Always
          securityContext:
            capabilities: {}
            privileged: false
        restartPolicy: Always
        dnsPolicy: ClusterFirst
- apiVersion: v1
  kind: Route
  metadata:
    name: "${APPLICATION_NAME}"
    annotations:
      description: Route for application's http service
      haproxy.router.openshift.io/disable_cookies: 'true'
  spec:
    host: "${APPLICATION_HOSTNAME}"
    tls:
      termination: edge
    to:
      kind: Service
      name: "${APPLICATION_NAME}"
- apiVersion: v1
  kind: Service
  metadata:
    name: "${APPLICATION_NAME}"
    annotations:
      description: The app server's http port
  spec:
    ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
    selector:
      deploymentConfig: "${APPLICATION_NAME}"
- apiVersion: v1
  kind: Service
  metadata:
    name: hazelcast-service
    annotations:
      description: Hazelcast port
  spec:
    ports:
    - protocol: TCP
      port: 5701
    selector:
      deploymentConfig: "${APPLICATION_NAME}"
